version: '3.8'

services:
  fastapi:
    container_name: fastapi
    restart: unless-stopped
    build:
      context: fast
    ports:
      - "8000:8000"
    networks:
      - lups
    environment:
      REDIS_BROKER_URL: redis
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      POSTGRES_BROKER_URL: postgres:5432
      POSTGRES_DATABASE: postgres
      TZ: "Europe/Tallinn"
    volumes:
      - image_data:/usr/src/app/images
  worker:
    container_name: worker
    restart: unless-stopped
    build:
      context: worker
    command: celery --app main worker --concurrency=1 --pool prefork
    environment:
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      NEWS_API_KEY: "test_key"
      TZ: "Europe/Tallinn"
    depends_on:
      - redis
      - postgres
    networks:
      - lups
  beat:
    container_name: beat
    build:
      context: worker
    command: celery --app beat beat --loglevel=debug
    depends_on:
      - redis
      - worker
    networks:
      - lups
    environment:
      TZ: "Europe/Tallinn"
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:6-alpine
    expose:
      - 6379
    networks:
      - lups
    volumes:
      - redis_data:/data
    environment:
      TZ: "Europe/Tallinn"
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:alpine
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      TZ: "Europe/Tallinn"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lups

networks:
  lups:
    driver: bridge

volumes:
  postgres_data:
  image_data:
  redis_data:
