version: '3.8'

services:
  fastapi:
    container_name: fastapi
    restart: unless-stopped
    build:
      context: fast
    ports:
      - "8000:8000"
    networks:
      - lups
    environment:
      - REDIS_BROKER_URL=redis
      - POSTGRES_USER=erik
      - POSTGRES_PASSWORD=erik
      - POSTGRES_BROKER_URL=postgres:5432
      - POSTGRES_DATABASE=postgres
    volumes:
      - image_data:/usr/src/app/images
  worker:
    container_name: worker
    restart: unless-stopped
    build:
      context: worker
    command: celery --app main worker --concurrency=1 --pool prefork
    environment:
      - POSTGRES_USER=erik
      - POSTGRES_PASSWORD=erik
    depends_on:
      - redis
      - postgres
    networks:
      - lups
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:6-alpine
    expose:
      - 6379
    networks:
      - lups
    volumes:
      - redis_data:/data
  postgres:
      container_name: postgres
      restart: unless-stopped
      image: postgres:alpine
      expose:
        - 5432
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: erik
        POSTGRES_PASSWORD: erik
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - lups
  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "erik@erik.com"
      PGADMIN_DEFAULT_PASSWORD: "erik"
      PGADMIN_DEFAULT_USER: "erik"
    networks:
      - lups

networks:
  lups:
    driver: bridge

volumes:
  postgres_data:
  image_data:
  redis_data:
