version: '3.8'

services:
  mysql:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: erik
        MYSQL_DATABASE: erik_db
        MYSQL_USER: erik
        MYSQL_PASSWORD: erik
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql  # Update the value to "mysql"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: erik
    ports:
      - 8080:80
    depends_on:
      - mysql

  flask:
    build:
      context: flaskr/.
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 5000:5000
    depends_on:
      - worker
      - redis

  worker:
    build: celeryr/.
    command: celery --app tasks.tasks.celery worker --concurrency=1
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1'  # Adjust the CPU limit as needed
          memory: 1G  # Adjust the memory limit as needed

  dashboard:
    build: celeryr/.
    command: celery --app tasks.tasks.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

volumes:
  mysql_data:
