version: '3.8'

services:
  worker:
    container_name: worker
    restart: unless-stopped
    build:
      context: worker
    command: celery --app main worker --concurrency=1 --pool prefork --queues=normal
    environment:
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      NEWS_API_KEY: "test_key"
      TZ: "Europe/Tallinn"
    depends_on:
      - redis
      - postgres
    networks:
      - lups
  music:
    container_name: music
    restart: unless-stopped
    build:
      context: music_worker
    command: celery --app main worker --concurrency=1 --pool prefork --queues=music
    environment:
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      TZ: "Europe/Tallinn"
    depends_on:
      - redis
      - postgres
    networks:
      - lups
  beat:
    container_name: beat
    build:
      context: worker
    command: celery --app beat beat --loglevel=debug
    depends_on:
      - redis
      - worker
    networks:
      - lups
    environment:
      TZ: "Europe/Tallinn"
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - lups
    volumes:
      - redis_data:/data
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lups


networks:
  lups:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  image_data:
