version: '3.8'

services:
  # !! run these commands to create a new certificate (not renew)
  # docker compose down
  # docker compose run -p 80:80 --rm  certbot certonly -d lyps.ee
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - cert_data:/etc/letsencrypt
    environment:
      TZ: "Europe/Tallinn"
  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: lups/.
      dockerfile: Dockerfile
    environment:
      TZ: "Europe/Tallinn"
    networks:
      - lups
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert_data:/etc/letsencrypt
  fastapi:
    container_name: fastapi
    restart: unless-stopped
    build:
      context: fast
    # todo expose 8000???
    ports:
      - "8000:8000"
    networks:
      - lups
    environment:
      REDIS_BROKER_URL: redis
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      POSTGRES_BROKER_URL: postgres:5432
      POSTGRES_DATABASE: postgres
      TZ: "Europe/Tallinn"
    volumes:
      - image_data:/usr/src/app/images
  worker:
    container_name: worker
    restart: unless-stopped
    build:
      context: worker
    command: celery --app main worker --concurrency=1 --pool prefork
    environment:
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      NEWS_API_KEY: ${NEWS_API_KEY}
      TZ: "Europe/Tallinn"
    volumes:
      - image_data:/usr/src/app/images
    depends_on:
      - redis
      - postgres
    networks:
      - lups
  beat:
    container_name: beat
    build:
      context: worker
    command: celery --app beat beat --loglevel=debug
    depends_on:
      - redis
      - worker
    networks:
      - lups
    environment:
      TZ: "Europe/Tallinn"
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:6-alpine
    expose:
      - 6379
    networks:
      - lups
    volumes:
      - redis_data:/data
    environment:
      TZ: "Europe/Tallinn"
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:alpine
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      TZ: "Europe/Tallinn"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lups

networks:
  lups:
    driver: bridge

volumes:
  cert_data:
  postgres_data:
  image_data:
  redis_data:
