version: '3.8'

services:
  worker:
    container_name: worker
    restart: unless-stopped
    build:
      context: worker
    command: celery --app main worker --concurrency=1 --pool prefork --queues=normal
    environment:
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      NEWS_API_KEY: "test_key"
      TZ: "Europe/Tallinn"
    depends_on:
      - redis
      - postgres
    networks:
      - lups
  music:
    container_name: music
    restart: unless-stopped
    build:
      context: music_worker
    # pool solo works better for priority queues
    command: celery --app=main worker --concurrency=1 --pool=solo --queues=music --loglevel=WARNING
    environment:
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
      TZ: "Europe/Tallinn"
    volumes:
      - music_data:/usr/src/app/music_data
    depends_on:
      - redis
      - postgres
    networks:
      - lups
  beat:
    container_name: beat
    build:
      context: scheduler
    command: celery --app beat beat --loglevel=debug
    depends_on:
      - redis
    networks:
      - lups
    environment:
      TZ: "Europe/Tallinn"
      MINUTE: "*/60"
      HOUR: "*"
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - lups
    volumes:
      - redis_data:/data
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lups
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "erik@erik.com"
      PGADMIN_DEFAULT_PASSWORD: "erik"
      PGADMIN_DEFAULT_USER: "erik"
    networks:
      - lups


networks:
  lups:
    driver: bridge

volumes:
  music_data:
  postgres_data:
  redis_data:
  image_data:
