# Use a lightweight Python base image
FROM python:3.9-slim

WORKDIR /usr/src/app

# postgre stuff
RUN apt-get update && apt-get -y install libpq-dev gcc

# Copy the requirements.txt file
COPY requirements.txt .

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask application code
COPY . .

# Expose the Flask server port
EXPOSE 5000

# Run the Flask application
CMD ["python", "run_server.py"]



