# pull official base image
FROM python:3.10.2-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# postgre stuff
RUN apt-get update && apt-get -y install libpq-dev gcc

# install dependencies
RUN pip install --upgrade pip
COPY celeryr/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy model
COPY celeryr/t5-model worker/t5-model

# copy db models
COPY flaskr/db_models/models.py worker/models.py

# copy project
COPY celeryr/worker worker