name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH into Server
        uses: actions/checkout@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Use your SSH private key stored in GitHub secrets

      - name: Copy Docker Compose Files to Server
        run: scp -r docker-compose.yaml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}

      - name: SSH into Server and Update Docker Containers
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd /path/to/your/app && docker-compose down && docker-compose pull && docker-compose up -d'
